### PR TITLE
Added base for unit testing

### LINKED ISSUE #23: Create tests base for REST client
Integrate testing model to repository to give developers ability to test their code as a port of the workflow with automatic runs on pull requests.

### PR DESCRIPTION
**Pull request by avan1235**
Closes #23 by introducing unit tests base and the scheme of testing. Created an issue to create tests base for integration tests with testcontainers-scala

### CODE REVIEW

**Comment by avan1235** [comment]
Have to wait for #25 to use new configuration of scalastyle running and add separate run for test directories with separate configuration file

**Comment by avan1235** [comment]
Had to move to ./sbtwrapper scalastyle checking code style as it gives the ability to have different configuration for style in tests (where for example we would like use magic numbers sometimes or another things taht are forbitten in codebase)

**Review by kantoniak — CHANGES_REQUESTED** [review]
There are multiple YAML formatter warnings:

    [document-start] missing document start "---"

Can you either add YAML headers or turn off warnings if we are not going to require them?

**Comment by kantoniak** [comment]
Also, could you later explain in the merge commit comment how `scalastyle` rules differ for testing?

**Comment by avan1235** [comment]
We would like to use for example "magic numbers in unit tests" I  think and I found that it is useful to manipulate these configurations separately. There are some other rules also that are missed in tests (try to pass null values to functions to check their behaviour when needed or use multiple times the same string without extracting it to variable)

**Comment by avan1235** [comment]
> There are multiple YAML formatter warnings:
> 
> ```
> [document-start] missing document start "---"
> ```
> 
> Can you either add YAML headers or turn off warnings if we are not going to require them?

will try to remove these wrnings

**Review by kantoniak — APPROVED** [review]

**Pull request merged**
